# Generated by Django 4.1.7 on 2023-03-24 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_Finder', '0002_rename_developing_company_developingcompany_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='platform',
            name='developingCompany',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game_Finder.developingcompany'),
        ),
    ]
