# Generated by Django 4.1.7 on 2023-04-06 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("game_Finder", "0003_game_rating_platform_developingcompany"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platform",
            name="developingCompany",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="game_Finder.developingcompany",
            ),
        ),
    ]
