# Generated by Django 4.1.7 on 2023-04-06 22:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game_Finder", "0004_alter_platform_developingcompany"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="rating",
            field=models.DecimalField(
                decimal_places=1,
                default=0.0,
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
            ),
        ),
    ]
