# Generated by Django 4.1.7 on 2023-03-24 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_Finder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Developing_Company',
            new_name='DevelopingCompany',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='developing_company',
            new_name='developingCompany',
        ),
    ]
