# Generated by Django 4.1.7 on 2023-04-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_Finder', '0003_game_rating_platform_developingcompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('min_age', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='developingCompany',
        ),
        migrations.RemoveField(
            model_name='game',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='game',
            name='platform',
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='userProfile',
            field=models.ManyToManyField(to='game_Finder.userprofile'),
        ),
        migrations.AddField(
            model_name='game',
            name='developingCompany',
            field=models.ManyToManyField(to='game_Finder.developingcompany'),
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(to='game_Finder.genre'),
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.ManyToManyField(to='game_Finder.platform'),
        ),
    ]
